---
kind: pipeline
type: docker
name: default

steps:
  - name: backend
    image: golang
    commands:
      - uname -a
      - pwd
      - go env
      - go build -tags nopie
      - go test -tags nopie